basePath: /
definitions:
  engine.Menu:
    properties:
      icon:
        type: string
      index:
        type: integer
      is_active:
        type: boolean
      main_menu:
        type: string
      name:
        type: string
      parent:
        type: integer
      sort:
        type: integer
      sub_parent:
        type: boolean
      url:
        type: string
    required:
    - icon
    - index
    - main_menu
    - name
    - sort
    - url
    type: object
  engine.ResponseStatus:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  engine.ResponseSuccess:
    properties:
      message:
        type: string
      status:
        type: boolean
    type: object
  engine.Role:
    properties:
      code:
        type: string
      name:
        type: string
    required:
    - code
    - name
    type: object
  engine.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
host: localhost:1234
info:
  contact: {}
  description: This is a document for API use in [Backend API Services]
  title: Swagger for [Backend API Services]
  version: "1.0"
paths:
  /api/v1/menus:
    get:
      consumes:
      - application/json
      parameters:
      - description: Limit Per Page
        in: query
        name: limit
        type: integer
      - description: Page Number
        in: query
        name: page
        type: integer
      - description: 'Sort By {ex: created_at asc | desc}'
        in: query
        name: sort
        type: string
      - description: 'Seraching by column {ex: id} action {ex: equals | contains |
          in}'
        in: query
        name: id.equals
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Menus
    post:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.Menu'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Menus
  /api/v1/menus/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Menus
    get:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Menus
    put:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.Menu'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Menus
  /api/v1/roles:
    get:
      consumes:
      - application/json
      parameters:
      - description: Limit Per Page
        in: query
        name: limit
        type: integer
      - description: Page Number
        in: query
        name: page
        type: integer
      - description: 'Sort By {ex: created_at asc | desc}'
        in: query
        name: sort
        type: string
      - description: 'Seraching by column {ex: id} action {ex: equals | contains |
          in}'
        in: query
        name: id.equals
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
    post:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.Role'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
  /api/v1/roles/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
    get:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
    put:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.Role'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
  /api/v1/users:
    get:
      consumes:
      - application/json
      parameters:
      - description: Limit Per Page
        in: query
        name: limit
        type: integer
      - description: Page Number
        in: query
        name: page
        type: integer
      - description: 'Sort By {ex: created_at asc | desc}'
        in: query
        name: sort
        type: string
      - description: 'Seraching by column {ex: id} action {ex: equals | contains |
          in}'
        in: query
        name: id.equals
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.User'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Users
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Users
    get:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.User'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Users
  /api/v1/version:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/engine.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/engine.ResponseStatus'
      tags:
      - Api Version
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
