basePath: /
definitions:
  engine.ResponseStatus:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  engine.ResponseSuccess:
    properties:
      message:
        type: string
      status:
        type: boolean
    type: object
  engine.Role:
    properties:
      code:
        type: string
      name:
        type: string
    required:
    - code
    - name
    type: object
host: localhost:1234
info:
  contact: {}
  description: This is a document for API use in [Backend API Services]
  title: Swagger for [Backend API Services]
  version: "1.0"
paths:
  /api/v1/menus:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Menus
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Menus
  /api/v1/menus/{id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Menus
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Menus
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Menus
  /api/v1/roles:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
    post:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.Role'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
  /api/v1/roles/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
    get:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
    put:
      consumes:
      - application/json
      parameters:
      - description: Pass session information to DBaaS Parameter
        in: path
        name: id
        required: true
        type: string
      - description: Pass session information to DBaaS Parameter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/engine.Role'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - Roles
  /version:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/engine.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/engine.ResponseStatus'
      tags:
      - Api Version
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
